// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCUqEC03tbkEW7x6kA7dJo-AEo6N9giZo',
    appId: '1:807439438124:web:9398624b4d250e9674dc89',
    messagingSenderId: '807439438124',
    projectId: 'education-app-b5e14',
    authDomain: 'education-app-b5e14.firebaseapp.com',
    storageBucket: 'education-app-b5e14.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk_d6ySkK2nlTN1Ut18XOY0-KkNGLo8XU',
    appId: '1:807439438124:android:153c96dd2bfc110374dc89',
    messagingSenderId: '807439438124',
    projectId: 'education-app-b5e14',
    storageBucket: 'education-app-b5e14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASvWqAiqr7yBxV4qwUDQ4uj83-GQWcUZ4',
    appId: '1:807439438124:ios:78c2f1ceffb5e5e374dc89',
    messagingSenderId: '807439438124',
    projectId: 'education-app-b5e14',
    storageBucket: 'education-app-b5e14.appspot.com',
    iosClientId: '807439438124-o0rh8t34rk7r35pnsakl662s70qc4p02.apps.googleusercontent.com',
    iosBundleId: 'com.vishu.educationApp',
  );
}
